### ISSUE TITLE
I think PHP minimum requirement is not 5.5.9?

### ISSUE THREAD

**Issue by Modelizer** [jmarcher/valet-linux#12]
Please check [composer.json](https://github.com/jmarcher/valet-linux/blob/master/composer.json#L36) which show PHP 5.5.9 as minimum requirment.

**Comment by ceesco53** [comment]
Upstream uses 7.0 in their instructions - https://www.laravel.com/docs/5.2/valet - I'd say it's reasonable to make 7.0 the minimum requirement even though upstream's composer.json is 5.5.9.  It would make it easier to support this fork in the long run.

**Comment by Modelizer** [comment]
The code is in 7.0 and my concern is composer.json should also be updated!

**Comment by jmarcher** [comment]
fixed

**Comment by jszobody** [comment]
Valet's own composer.json only requires 5.5.9 though:

https://github.com/laravel/valet/blob/master/composer.json#L27

I realize their instructions on the web mention PHP7, but I'm successfully running the latest Valet with PHP 5.6 on my Mac. Using it with a PHP app that can't be upgraded to PHP7 at this point.

Would like to have our linux team members use this repo for Valet on linux, but bumping minimum to PHP7 is problematic for us.

Since Laravel's Valet doesn't require PHP7, I don't think this should have been changed.

**Comment by Modelizer** [comment]
@jszobody Yes, I agree with you but right now the code is tightly built with PHP7.
Is it possible for you to propose a PR to downgrade to PHP5.6?

If you can do so then please ask @jmarcher before submitting PR. 

Thanks.

**Comment by jszobody** [comment]
By "the code" you're referring then to this fork specifically? I guess I haven't looked at the source of this repo very closely. I just assumed (hoped?) it would be pretty close to Laravel's Valet.

Maybe it's not feasible then. If @jmarcher wrote his code to be PHP7 only, I doubt there's room to go back.

**Comment by Modelizer** [comment]
Yes @jszobody, I'm referring "the code" to this fork specifically. :)
