### ISSUE TITLE
DnsMasq on Arch address problem

### ISSUE THREAD

**Issue by jmarcher** [jmarcher/valet-linux#3]
When I ping any .dev domain the response is 127.0.53.53 not 127.0.0.1 as expected.

Any ideas what is happening here? has anyone a solution?

**Comment by adriaanzon** [comment]
This is because .dev is actually a reserved TLD (by Google in this case).  Several other TLDs have this as well, for example .app, .drive, or even .meme

[This article](https://www.icann.org/news/announcement-2-2014-08-01-en) explains why the response is 127.0.53.53

So this means dnsmasq is actually not doing anything.  I have got the same problem on Arch, not sure how to fix it.

**Comment by ogg1980** [comment]
Make sure you actually are using 127.0.0.1 as a nameserver (check your /etc/resolv.conf). Add 127.0.0.1 at the top and it should work.
